version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "rodrigosantiag"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "rodrigosantiag"
