DROP TABLE IF EXISTS public.accounts CASCADE;

DROP TABLE IF EXISTS public.brokers CASCADE;

DROP TABLE IF EXISTS public.strategies CASCADE;

DROP TABLE IF EXISTS public.trades CASCADE;

DROP TABLE IF EXISTS public.users CASCADE;
