name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  Deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: AWS credentials
        if: github.ref == 'refs/heads/develop'
        uses: rodrigosantiag/github-actions/aws-configure@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      - name: AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: noverde/github-actions/aws-configure@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      - name: Install dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make coverage

      - name: Deploy
        run: make deploy

      - name: Database migration
        run: make migrate
