name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main

jobs:
  Test:
    name: Lint and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make coverage
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
